// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stipjdsfdiitnuqdbonc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0aXBqZHNmZGlpdG51cWRib25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mzg3OTAsImV4cCI6MjA2NTMxNDc5MH0.pXdaVF0X64WLwJiAqfw8wLHp2PNFiggIAL3lEBfp07I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);